---
- name: Generate Hosts File
  hosts: masters
  become: true
  gather_facts: true
  tasks:
    - name: Installing Prerequisites for Kubernetes
      apt: 
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - vim
          - software-properties-common
          - policycoreutils
        state: present

    - name: Add an apt signing key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt repository for stable version
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Execute the script
      command: sh /vagrant/docker.sh
 
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Disable SELinux
      selinux:
        state: disabled
      register: result
      failed_when: result.msg | default('ok', True) is not search('(^ok$|libselinux-python|(SELinux state changed))')
    - name: Disable SWAP
      command: swapoff -a

    - name: add Kubernetes apt-key for APT repository
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: add Kubernetes APT repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: 'kubernetes'

    - name: Install Kubernetes Package
      command: sh /vagrant/kubernetes.sh

    # - name: Install Kubernetes Package
    #   apt:
    #     name: "{{packages}}"
    #     state: present
    #   vars:
    #     packages:
    #       - kubelet
    #       - kubeadm
    #       - kubectl
    - name: Enable / Start kubelet Service
      service:
        name: kubelet
        state: started
        enabled: yes
    - name: Letting iptables see bridged traffic
      copy:
        src: /vagrant/files/k8s.conf
        dest: /etc/sysctl.d/k8s.conf
        owner: root
        group: root
        mode: '0644'
    - name: Reload sysctl config for iptables
      command: sysctl --system


