---
- name: Generate Hosts File
  hosts: member
  become: true
  gather_facts: true
  tasks:
    - name: Usesystemd
      command: sh /vagrant/usesystemd.sh
    - name: Generated token - 1.
      local_action: shell sed -n 69,72p ./token > ./mastertoken
    - name: Copy master token
      copy:
        src: /vagrant/mastertoken
        dest: /tmp/join-command.sh
        owner: root
        group: root
        mode: '0777'
    - name: Generated token - 2.
      lineinfile:
        path: /tmp/join-command.sh
        line: '\ --apiserver-advertise-address {{ hostvars[inventory_hostname].ansible_eth1.ipv4.address}}'

    # - name: Generated token - 2.
    #   shell: sed -i 's/\b:80\b/& --apiserver-advertise-address {{hostvars[inventory_hostname].ansible_eth1.ipv4.address}} /' /tmp/join-command.sh
    #   debug:
    #     msg: "{{ hostvars[inventory_hostname].ansible_eth1.ipv4.address}}"
#      command: sh -c 'echo --apiserver-advertise-address "{{ hostvars[inventory_hostname].ansible_eth1.ipv4.address}}" /' /tmp/join-command.sh'

    - name: Add new Kubernetes master member
      command: sh /tmp/join-command.sh
