apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSetting
metadata:
  name: default
  namespace: openshift-compliance
autoUpdateRemediations: true 
autoApplyRemediations: true 
rawResultStorage:
  pvAccessModes:
  - ReadWriteOnce 
  rotation: 3 
  size: 1Gi 
roles:
- worker 
- master 
schedule: 0 1 * * * 
