apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeperpolicy
spec:
  destination:
    name: ''
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  source:
    path: opa-gatekeeper/deploy/used_policies
    repoURL: 'https://github.com/lanasak/Stage_FlowFactor'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
