apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cis-scan
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-compliance
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: compliance-operator/scan
    repoURL: https://github.com/lanasak/Stage_FlowFactor
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true